
services:
  tf-serving:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # REST API
      - "8500:8500"  # gRPC
    volumes: # mount thư mục từ host vào container
      - ./backend/weight:/models
    restart: always # tự động restart container nếu crash hoặc stop
    networks:
      - app-network # kết nối đến mạng app-network
  # FastAPI Backend service (service 2)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.fastapi
    ports:
      - "6879:6879"
    depends_on:
      - tf-serving # đảm bảo tf serving khởi động trước backend
    environment:
      - TF_SERVING_URL=http://tf-serving:8501 # url để backend kết nối đến tf serving
    restart: always
    networks:
      - app-network
  # Frontend service
  frontend:
    build:
      context: ./frondend
      dockerfile: Dockerfile
    environment:
      - VITE_BASE_URL_API_BACKEND=/api
    ports:
      - "80:80"
    depends_on: # phụ thuộc vào backend để đảm bảo backend đã khởi động trước
      - backend
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
# tất cả services kết nối với nhau cùng app-network, giao tieesp với nhau qua tên 
# TF Serving: Xử lý inference cho models
# FastAPI Backend: API gateway và xử lý logic
# Frontend: Giao diện người dùng