version: '3'
services:
  tf-serving:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # REST API
      - "8500:8500"  # gRPC
    volumes: # mount thư mục từ host vào container
      - ./backend/weight/convenetiny_full.keras:/models/skin_cancer/1/model.keras
      - ./backend/weight/convenetiny_1_2_balanced.keras:/models/autism/1/model.keras
      - ./backend/model.config:/models/model.config
    restart: always # tự động restart container nếu crash hoặc stop

  # FastAPI Backend service (service 2)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.fastapi
    ports:
      - "6879:6879"
    depends_on:
      - tf-serving # đảm bảo tf serving khởi động trước backend
    environment:
      - TF_SERVING_URL=http://tf-serving:8501 # url để backend kết nối đến tf serving
    restart: always

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on: # phụ thuộc vào backend để đảm bảo backend đã khởi động trước
      - backend
    restart: always
# TF Serving: Xử lý inference cho models
# FastAPI Backend: API gateway và xử lý logic
# Frontend: Giao diện người dùng